server:
  port: 9000
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat  #开启监控过滤器
  redis:
    host: 192.168.188.130
    port: 6379
application:
  name: SCW-ORDER
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/order/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-ORDER
    prefer-ip-address: true
logging:
  level:
    com:
      offcn: info #debug -->info --->warn-->error
  file:
    path: D:\log\scw-project