server:
  port: 8000
spring:
  application:
    name: SCW-PROJECT
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat  #开启监控过滤器
  redis:
    host: 192.168.188.130
    port: 6379
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/project/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      offcn: info #debug -->info --->warn-->error
  file:
    path: D:\log\scw-project

#oss的配置
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: offcn202103031102.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4Fz8yLvFUyfPMzvhBJvL
  accessKeySecret: PasmTPBt9m7eGN1j4raEDS2e0YnRhS
  bucketName: offcn202103031102